-- DDL generated by Postico 1.4.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------
CREATE TABLE jokes (
    id text PRIMARY KEY,
    joke text,
    votes integer DEFAULT 0
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX jokes_pkey ON jokes(id text_ops);
